import React, { useState } from 'react';
import { Upload, FileText, List, BarChart3, ArrowDownToLine, PlusCircle, LightbulbIcon, Download } from 'lucide-react';
import Header from './components/Header';
import FileUpload from './components/FileUpload';
import EnrichmentOptions from './components/EnrichmentOptions';
import PreviewData from './components/PreviewData';
import SegmentationScoring from './components/SegmentationScoring';
import ExportOptions from './components/ExportOptions';
import Stepper from './components/Stepper';
import MarketplaceBrowser from './components/MarketplaceBrowser';
import DataLibrary from './components/DataLibrary';
import Reports from './components/Reports';

// Sample data for development
const sampleLeads = Array.from({ length: 30 }, (_, i) => ({
  id: i + 1,
  name: `Data Source ${i + 1}`,
  email: i % 3 === 0 ? '' : `provider${i + 1}@example.com`,
  phone: i % 4 === 0 ? '' : `+1 555-${100 + i}`,
  company: `Provider ${String.fromCharCode(65 + (i % 26))}`,
  title: i % 5 === 0 ? '' : `${['Premium', 'Basic', 'Enterprise', 'Developer', 'Custom'][i % 5]} Data Package`,
  linkedin: i % 3 !== 0,
  industry: i % 4 === 0 ? '' : ['Financial Services', 'Healthcare', 'Retail', 'Technology', 'Public Sector'][i % 5],
  companySize: ['1-10', '11-50', '51-200', '201-1000', '1000+'][i % 5],
  datasetType: ['API', 'File', 'Stream', 'Database', 'ML Model'][i % 5],
  updateFrequency: ['Daily', 'Weekly', 'Monthly', 'Quarterly', 'Real-time'][i % 5],
  awsRegions: ['us-east-1', 'us-west-2', 'eu-west-1', 'ap-southeast-1', 'global'][i % 5],
}));

// Generate enriched sample data
const getEnrichedSampleLeads = (leads: any[], enrichmentOptions: string[]) => {
  return leads.map(lead => {
    const enriched = { ...lead };
    
    // Fill in missing data based on enrichment options
    if (enrichmentOptions.includes('metadata')) {
      if (!enriched.datasetType) enriched.datasetType = ['API', 'File', 'Stream', 'Database', 'ML Model'][lead.id % 5];
      if (!enriched.updateFrequency) enriched.updateFrequency = ['Daily', 'Weekly', 'Monthly', 'Quarterly', 'Real-time'][lead.id % 5];
      if (!enriched.awsRegions) enriched.awsRegions = ['us-east-1', 'us-west-2', 'eu-west-1', 'ap-southeast-1', 'global'][lead.id % 5];
    }
    
    if (enrichmentOptions.includes('provider')) {
      if (!enriched.email) enriched.email = `provider${enriched.id}@${enriched.company.toLowerCase().replace(' ', '')}.com`;
      if (!enriched.phone) enriched.phone = `+1 555-${100 + enriched.id}`;
      enriched.supportLevel = ['Basic', 'Standard', 'Premium', 'Enterprise', '24/7'][enriched.id % 5];
    }
    
    if (enrichmentOptions.includes('integration')) {
      enriched.apiDocs = true;
      enriched.sampleCode = ['Python', 'Java', 'JavaScript', 'C#', 'Go'][enriched.id % 5];
      enriched.awsServiceIntegrations = ['S3', 'Lambda', 'Glue', 'SageMaker', 'QuickSight'][enriched.id % 5];
    }
    
    if (enrichmentOptions.includes('insights')) {
      enriched.dataQualityScore = Math.floor(Math.random() * 100) + 1;
      enriched.usageTrend = [
        'Growing adoption in financial sector', 
        'Popular for healthcare analytics', 
        'Common in retail forecasting', 
        'Trending in ML model training', 
        'Widely used for compliance'
      ][enriched.id % 5];
      enriched.compatibleLyzrAgents = [
        'Data Cleansing Agent',
        'Pattern Recognition Agent',
        'Prediction Model Agent',
        'Visualization Agent',
        'Integration Agent'
      ][enriched.id % 5];
    }
    
    return enriched;
  });
};

// Sample segments - in a real app, these would be generated by AI
const sampleSegments = [
  {
    id: 1,
    name: 'Financial Analytics Datasets',
    count: 12,
    criteria: 'High-quality financial data with daily updates, compatible with AWS QuickSight',
    conversion: '25%'
  },
  {
    id: 2,
    name: 'Healthcare Compliance Data',
    count: 8,
    criteria: 'HIPAA-compliant healthcare datasets with strong documentation',
    conversion: '18%'
  },
  {
    id: 3,
    name: 'Retail Consumer Insights',
    count: 15,
    criteria: 'Consumer behavior datasets with demographic segmentation',
    conversion: '15%'
  },
  {
    id: 4,
    name: 'Machine Learning Ready',
    count: 7,
    criteria: 'Datasets optimized for training ML models with SageMaker integration',
    conversion: '22%'
  },
  {
    id: 5,
    name: 'Real-time Data Streams',
    count: 10,
    criteria: 'Real-time data feeds with immediate updates and low latency',
    conversion: '12%'
  },
  {
    id: 6,
    name: 'Globally Distributed Data',
    count: 18,
    criteria: 'Multi-region datasets available across all AWS regions',
    conversion: '5%'
  }
];

const App = () => {
  const [step, setStep] = useState(1);
  const [uploadedLeads, setUploadedLeads] = useState<any[]>(sampleLeads); // For demonstration
  const [enrichmentOptions, setEnrichmentOptions] = useState<string[]>([]);
  const [enrichedLeads, setEnrichedLeads] = useState<any[]>([]);
  const [showRecommendations, setShowRecommendations] = useState(false);
  const [darkMode, setDarkMode] = useState(false);
  const [showMarketplaceBrowser, setShowMarketplaceBrowser] = useState(false);
  const [activeView, setActiveView] = useState<'dashboard' | 'library' | 'reports'>('dashboard');
  
  const handleFileUpload = (file: File) => {
    // In a real app, we would parse the file here
    // For demo purposes, we'll just use the sample data
    setUploadedLeads(sampleLeads);
    setStep(2);
  };
  
  const handleEnrichmentSelect = (options: string[]) => {
    setEnrichmentOptions(options);
    // Simulate API call to enrich data
    setEnrichedLeads(getEnrichedSampleLeads(uploadedLeads, options));
    setStep(3);
  };
  
  const handleValidate = () => {
    setStep(4);
  };
  
  const handleSegmentContinue = () => {
    setStep(5);
  };
  
  const handleExport = () => {
    alert('Data export initiated!');
    // This would trigger an actual export in a real app
  };
  
  const steps = [
    { id: 1, title: 'Upload', icon: <Upload className="w-5 h-5" /> },
    { id: 2, title: 'Enrich', icon: <FileText className="w-5 h-5" /> },
    { id: 3, title: 'Preview', icon: <List className="w-5 h-5" /> },
    { id: 4, title: 'Segment', icon: <BarChart3 className="w-5 h-5" /> },
    { id: 5, title: 'Export', icon: <ArrowDownToLine className="w-5 h-5" /> }
  ];
  
  const toggleDarkMode = () => {
    setDarkMode(!darkMode);
    // In a real implementation, you would apply dark mode classes to the HTML element
  };
  
  return (
    <div className={`min-h-screen ${darkMode ? 'bg-gray-900 text-white' : 'bg-gray-50'}`}>
      <Header onNavigate={(view) => setActiveView(view)} activeView={activeView} />
      
      <main className="container mx-auto px-4 py-8 max-w-7xl">
        <div className="mb-8 flex items-center justify-between">
          <div className="max-w-2xl">
            <h1 className={`text-3xl font-bold ${darkMode ? 'text-white' : 'text-gray-900'} mb-2`}>
              {activeView === 'dashboard' && 'AWS Data Marketplace Integration'}
              {activeView === 'library' && 'AWS Data Marketplace Library'}
              {activeView === 'reports' && 'AWS Data Marketplace Reports'}
            </h1>
            <p className={`${darkMode ? 'text-gray-300' : 'text-gray-600'}`}>
              {activeView === 'dashboard' && 'Find, enrich, and analyze AWS Data Marketplace sources with Lyzr\'s intelligent agents'}
              {activeView === 'library' && 'Browse and manage your AWS Data Marketplace datasets'}
              {activeView === 'reports' && 'Monitor usage, performance, and insights from your data sources'}
            </p>
          </div>
          <div className="flex items-center">
            <div className="mr-4 flex space-x-3">
              <button 
                onClick={() => setShowMarketplaceBrowser(true)}
                className="px-3 py-1.5 text-xs rounded-md flex items-center bg-[#FF9900] text-white hover:bg-[#E68A00] transition"
              >
                Browse Marketplace
              </button>
              <button 
                onClick={toggleDarkMode}
                className={`px-3 py-1.5 text-xs rounded-md flex items-center ${
                  darkMode 
                    ? 'bg-gray-700 text-white' 
                    : 'bg-gray-200 text-gray-800'
                }`}
              >
                {darkMode ? 'Light Mode' : 'Dark Mode'}
              </button>
            </div>
            <img 
              src="/images/aws-logo.png" 
              alt="AWS Marketplace" 
              className="h-10" 
            />
          </div>
        </div>
        
        {activeView === 'dashboard' && (
          <>
            <div className="mb-8">
              <Stepper steps={steps} currentStep={step} />
            </div>
            
            <div className={`${darkMode ? 'bg-gray-800 border-gray-700' : 'bg-white border-gray-200'} rounded-xl p-6 shadow-sm border`}>
              {step === 1 && (
                <FileUpload onFileUpload={handleFileUpload} />
              )}
              
              {step === 2 && (
                <EnrichmentOptions 
                  leads={uploadedLeads} 
                  onEnrichmentSelect={handleEnrichmentSelect} 
                />
              )}
              
              {step === 3 && (
                <PreviewData 
                  originalLeads={uploadedLeads} 
                  enrichedLeads={enrichedLeads} 
                  selectedOptions={enrichmentOptions}
                  onValidate={handleValidate}
                />
              )}
              
              {step === 4 && (
                <SegmentationScoring 
                  enrichedLeads={enrichedLeads} 
                  segments={sampleSegments}
                  onContinue={handleSegmentContinue}
                />
              )}
              
              {step === 5 && (
                <ExportOptions 
                  enrichedLeads={enrichedLeads} 
                  segments={sampleSegments}
                  onExport={handleExport}
                />
              )}
            </div>
          </>
        )}
        
        {activeView === 'library' && <DataLibrary />}
        
        {activeView === 'reports' && <Reports />}
        
        {/* Floating AI Recommendations Button */}
        <div className="fixed bottom-8 right-8">
          <button
            onClick={() => setShowRecommendations(!showRecommendations)}
            className="bg-[#FF9900] hover:bg-amber-500 text-white p-4 rounded-full shadow-lg transition-all"
          >
            <LightbulbIcon className="w-6 h-6" />
          </button>
        </div>
        
        {/* AI Recommendations Panel */}
        {showRecommendations && (
          <div className="fixed bottom-24 right-8 w-80 bg-white rounded-lg shadow-xl border border-gray-200 p-4 animate-fade-in">
            <div className="flex justify-between items-center mb-3">
              <h3 className="text-md font-bold text-gray-800">AI Recommendations</h3>
              <button 
                onClick={() => setShowRecommendations(false)}
                className="text-gray-400 hover:text-gray-600"
              >
                ×
              </button>
            </div>
            
            <div className="space-y-3 max-h-80 overflow-y-auto">
              <div className="p-3 bg-blue-50 rounded-lg border border-blue-100">
                <div className="text-sm font-medium text-blue-800 mb-1">Try AWS SageMaker Integration</div>
                <p className="text-xs text-blue-600">Your dataset would benefit from ML models available through AWS SageMaker. Try connecting for predictive insights.</p>
              </div>
              
              <div className="p-3 bg-green-50 rounded-lg border border-green-100">
                <div className="text-sm font-medium text-green-800 mb-1">Financial Data Opportunity</div>
                <p className="text-xs text-green-600">We've detected 8 financial datasets with high quality and update frequency. Prioritize these for analysis.</p>
              </div>
              
              <div className="p-3 bg-amber-50 rounded-lg border border-amber-100">
                <div className="text-sm font-medium text-amber-800 mb-1">Data Quality Enhancement</div>
                <p className="text-xs text-amber-600">Try our Data Cleansing Agent to fix 12 detected inconsistencies across your datasets.</p>
              </div>
            </div>
            
            <div className="mt-3 pt-3 border-t border-gray-100">
              <button className="w-full px-3 py-2 bg-indigo-600 text-white text-xs font-medium rounded-md hover:bg-indigo-700">
                Apply All Recommendations
              </button>
            </div>
          </div>
        )}
        
        {/* AWS Marketplace Browser Modal */}
        {showMarketplaceBrowser && (
          <MarketplaceBrowser onClose={() => setShowMarketplaceBrowser(false)} />
        )}
        
        {/* Quick Actions Bar */}
        <div className="fixed bottom-0 left-0 right-0 bg-white border-t border-gray-200 py-2 px-4 flex justify-between">
          <div className="flex items-center space-x-2 text-sm text-gray-500">
            {activeView === 'dashboard' && <span>Step {step} of {steps.length}</span>}
            {activeView === 'dashboard' && step > 1 && (
              <button 
                onClick={() => setStep(step - 1)}
                className="px-2 py-1 text-xs bg-gray-100 rounded hover:bg-gray-200"
              >
                Back
              </button>
            )}
          </div>
          
          <div className="flex space-x-2">
            <button className="px-3 py-1.5 text-xs bg-white border border-gray-200 rounded-md text-gray-700 hover:bg-gray-50 flex items-center">
              <Download className="w-3 h-3 mr-1" />
              Save Progress
            </button>
            <button className="px-3 py-1.5 text-xs bg-white border border-gray-200 rounded-md text-gray-700 hover:bg-gray-50 flex items-center">
              <PlusCircle className="w-3 h-3 mr-1" />
              Add New Source
            </button>
          </div>
        </div>
        
        <div className="mt-8 bg-gradient-to-r from-[#232F3E] to-[#00A1C9] text-white p-6 rounded-lg shadow-md">
          <div className="flex items-start">
            <div className="mr-6">
              <h2 className="text-xl font-bold mb-2">Lyzr + AWS Data Marketplace</h2>
              <p className="text-white/90 mb-4">
                Unlock the full potential of AWS Data Marketplace with Lyzr's AI agents. Our platform helps you discover, 
                process, and generate insights from premium data sources with minimal code.
              </p>
              <div className="flex space-x-4">
                <a href="#" className="bg-[#FF9900] hover:bg-amber-500 text-white px-4 py-2 rounded-md font-medium text-sm">
                  Explore Agents
                </a>
                <a href="#" className="bg-white/10 hover:bg-white/20 text-white px-4 py-2 rounded-md font-medium text-sm">
                  Learn More
                </a>
              </div>
            </div>
            <img 
              src="https://d1.awsstatic.com/Developer%20Marketing/eventbridge/product-icon_AWS-Marketplace_64_squid.25918865fc9dd1b2c27f9935ad906371c1fe8dc1.png" 
              alt="AWS Data Exchange" 
              className="w-96 h-auto rounded-md shadow-lg hidden lg:block" 
            />
          </div>
        </div>
      </main>
    </div>
  );
};

export default App;
